# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Python base image
FROM python:3.11-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt pyproject.toml ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Install the application in development mode
RUN pip install -e .

# Set the default entrypoint
ENTRYPOINT ["python", "-m", "transfermarkt_mcp"]
